### ISSUE TITLE
Correction in Tiva_i2c.c line#119

### ISSUE THREAD

**Issue by nsparag** [mahengunawardena/Tiva_I2C_Nokia_ADXL345#1]
```
Line #119 in Tiva_i2c.c should be corrected.
```

By this line we are WRITING to slave device so the 3rd parameter to the function should be 'false' else the writeI2C0() will not work.
original :    I2CMasterSlaveAddrSet(I2C0_BASE, device_address, true);
corrected : I2CMasterSlaveAddrSet(I2C0_BASE, device_address, false);

**Comment by mahengunawardena** [comment]
Thank you

**Comment by PJMonty** [comment]
Hi,
It's not enough to say "thank you" when someone correctly points out an error in your code.  The proper thing to do is to fix your code so that others don't download it and try to use it.  It's been 5 years, so perhaps now is the time to update your repository with working code.

**Comment by mahengunawardena** [comment]
@PJMonty, You are welcome to make the necessary changes. I have moved on from this project and I don't have have necessary hardware to test the code. At the time of posting the code the SW was working on the respective HW.
